spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  title: Ticket Service
  version: 1.0
#properties
kafka:
  topic:
    name: "ticket-activity"
    partition: 3
  broker: "2"

feign:
  client:
    event:
      name: "event"
      url: "http://localhost:9001"
      path: "/getAllEvents"
    user:
      name: "user"
      url: "http://localhost:9004"
      path: "/getAllUsers"

server:
  port: 9007